version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    build: ./database
    volumes:
      - ./db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs
    environment:
      MYSQL_DATABASE: DcardAssignment
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"