version: '3'
services:
  app:
    environment:
      GIN_MODE: release
      MYSQL_USERNAME: root
      MYSQL_IP: db
      MYSQL_PORT: 3306
      MYSQL_Database: DcardAssignment
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    restart: always
  db:
    build: ./database
    volumes:
      - ./dockerVolumes/db:/var/lib/mysql
      - ./dockerVolumes/conf:/etc/mysql/conf.d
      - ./dockerVolumes/logs:/logs
    environment:
      MYSQL_DATABASE: DcardAssignment
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0
    volumes:
      - ./dockerVolumes/redis_data:/data