version: '3'
services:
  app:
    environment:
      MYSQL_USERNAME: root
      MYSQL_IP: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: AdDeliveryLink
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    restart: always
  db:
    build: ./schema
    volumes:
      - db-db:/var/lib/mysql
      - db-conf:/etc/mysql/conf.d
      - db-logs:/logs
    environment:
      MYSQL_DATABASE: AdDeliveryLink
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
volumes:
  redis-data:
  db-db:
  db-conf:
  db-logs: