name: Test

on:
  push:
    paths-ignore:
      - '/jmeterDocs/**'
      - 'README'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '/jmeterDocs/**'
      - 'README'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: src/go.sum

      - name: Install dependencies
        run: go get .
        working-directory: ./src

      - name: Run build
        run: go build -v
        working-directory: ./src

      - name: Run tests
        run: go test -v ./tests/...
        working-directory: ./src
  build-app:
    needs: 
      - test
    uses: ./.github/workflows/app-docker-image.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
  build-db:
        needs: 
          - test
        uses: ./.github/workflows/db-docker-image.yml
        secrets: inherit
        permissions:
          contents: read
          packages: write